name: CI

on: [push, pull_request]

jobs:
  sast_scan:
    name: SAST test
    runs-on: ubuntu-latest
    steps:
      - name: run checkout action
        uses:  actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.11
      - name: install bandit
        run: pip install bandit
      - name: run bandit
        run: bandit -r .
        
